language: generic

before_install:
  - sudo apt-get install python-pygments

install:
  - source ./texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

before_script: cd $TRAVIS_BUILD_DIR/proposal/

script:
  - pdflatex --shell-escape ./proposal.tex

deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN}
  file:
    - ./proposal.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master

notifications:
  email: false
